spring.datasource.url=jdbc:oracle:thin:@//tndexacxvm-scan.crisexcax.org:1521/test.crisexcax.org
spring.datasource.username=tms3t
spring.datasource.password=tms3t
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.hibernate.ddl-auto=none

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

app.upload-dir=uploads/gstin

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=shurak949@gmail.com
spring.mail.password=alyhypvdbnxxlzre
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
