-- ============================================================================
-- schema.sql
-- Customer Registration Application — Consolidated Oracle Schema
-- ============================================================================
-- This file is a REFERENCE of the complete schema. For fresh setup, run the
-- individual scripts in order (01 → 02 → 03 → 06). For test data add 04.
--
-- DO NOT run this file if you have already run the individual scripts —
-- it will fail on "already exists" errors.
-- ============================================================================

-- ═══════════════════════════════════════════════════════════════════════════
-- TABLES (from 01_create_tables.sql)
-- ═══════════════════════════════════════════════════════════════════════════

-- FOIS Global Customer Master Table
CREATE TABLE MEMGLBLCUST (
    MAVGLBLCUSTCODE     VARCHAR2(4)     NOT NULL,
    MAVGLBLCUSTNAME     VARCHAR2(45),
    MAVGLBLCUSTADDRTEXT VARCHAR2(100),
    MAVGNBLCUSTCITYNAME VARCHAR2(30),
    MAVCENTBLNG         VARCHAR2(1),
    MAVPCOCODE          VARCHAR2(3),
    MAVEDMNDFLAG        VARCHAR2(1),
    MADIMPLDATE         DATE,
    MAVIMPLREMK         VARCHAR2(35),
    MADEDMNDDATE        DATE
);

-- FOIS Handling Agent Master Table
CREATE TABLE MEMGLBLHNDGAGNT (
    MAVHNDGAGNTCODE     VARCHAR2(4)     NOT NULL,
    MAVHNDGAGNTNAME     VARCHAR2(45)    NOT NULL,
    MAVHNDGAGNTADDRTEXT VARCHAR2(100),
    MAVHNDGAGNTCITYNAME VARCHAR2(30),
    MAVCENTBLNG         VARCHAR2(1),
    MAVPCOCODE          VARCHAR2(3),
    MAVEDMNDFLAG        VARCHAR2(1),
    MADIMPLDATE         DATE,
    MAVIMPLREMK         VARCHAR2(35),
    MADEDMNDDATE        DATE
);

-- FOIS Wagon Ownership Table
CREATE TABLE MEMWGONOWNRSHIP (
    MAVWGONOWNRSHIPCODE VARCHAR2(4)     NOT NULL,
    MAVWGONOWNRSHIPDESC VARCHAR2(100),
    MACPRVTPRTYCODE     VARCHAR2(100),
    MACOWNRVLDTYFLAG    CHAR(1),
    MADDATELASTUPDT     DATE,
    MAVRMRK             VARCHAR2(50)
);

-- FOIS Wagon Owner Party Table
CREATE TABLE MEMWGONOWNRPRTY (
    MAVWGONOWNRPRTYCODE VARCHAR2(5)     NOT NULL,
    MAVWGONOWNRPRTYDESC VARCHAR2(50)
);

-- Customer Master Table
CREATE TABLE MEMCUSTOMER (
    MAVCUSTOMERCODE     VARCHAR2(10)    NOT NULL,
    MAVCUSTOMERNAME     VARCHAR2(100)   NOT NULL,
    MAVADDRESS          VARCHAR2(255),
    MAVCITY             VARCHAR2(50),
    MAVPINCODE          VARCHAR2(10),
    MAVPCOCODE          VARCHAR2(3),
    MAVPAN              VARCHAR2(10),
    MAVEMAIL            VARCHAR2(100),
    MAVMOBILE           VARCHAR2(15),
    MAVGLBLCUSTCODE     VARCHAR2(4),
    MAVHNDGAGNTCODE     VARCHAR2(4),
    MACACTIVEFLAG       CHAR(1)         DEFAULT 'Y',
    MADCREATEDDATE      DATE            DEFAULT SYSDATE,
    MADUPDATEDDATE      DATE            DEFAULT SYSDATE
);

-- Customer GSTIN Table
CREATE TABLE MEMCUSTOMERGSTIN (
    GSTINID             NUMBER          NOT NULL,
    MAVCUSTOMERCODE     VARCHAR2(10)    NOT NULL,
    MAVSTATE            VARCHAR2(50)    NOT NULL,
    MAVSTATECODE        VARCHAR2(2),
    MAVGSTINNUMBER      VARCHAR2(15)    NOT NULL,
    MAVGSTINFILE        BLOB,
    MAVGSTINFILENAME    VARCHAR2(255),
    MAVGSTINFILETYPE    VARCHAR2(50),
    MAVGSTINFILEPATH    VARCHAR2(500),
    MACACTIVEFLAG       CHAR(1)         DEFAULT 'Y',
    MADCREATEDDATE      DATE            DEFAULT SYSDATE,
    MADUPDATEDDATE      DATE            DEFAULT SYSDATE
);

-- GSTIN ID auto-generation sequence
CREATE SEQUENCE SEQ_MEMCUSTOMERGSTIN_GSTINID
    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- User Authentication Table (from 06_create_users_table.sql)
CREATE TABLE MEMUSERS (
    MAVUSERID           NUMBER GENERATED ALWAYS AS IDENTITY,
    MAVEMAIL            VARCHAR2(255)   NOT NULL,
    MAVUSERNAME         VARCHAR2(100)   NOT NULL,
    MAVPASSWORDHASH     VARCHAR2(255)   NOT NULL,
    MACACTIVEFLAG       CHAR(1)         DEFAULT 'Y',
    MADCREATEDDATE      DATE            DEFAULT SYSDATE,
    CONSTRAINT PK_MEMUSERS         PRIMARY KEY (MAVUSERID),
    CONSTRAINT UQ_MEMUSERS_EMAIL   UNIQUE (MAVEMAIL),
    CONSTRAINT UQ_MEMUSERS_UNAME   UNIQUE (MAVUSERNAME)
);

-- ═══════════════════════════════════════════════════════════════════════════
-- CONSTRAINTS (from 02_constraints.sql)
-- ═══════════════════════════════════════════════════════════════════════════

-- Primary Keys
ALTER TABLE MEMGLBLCUST       ADD CONSTRAINT PK_MEMGLBLCUST       PRIMARY KEY (MAVGLBLCUSTCODE);
ALTER TABLE MEMGLBLHNDGAGNT   ADD CONSTRAINT PK_MEMGLBLHNDGAGNT   PRIMARY KEY (MAVHNDGAGNTCODE);
ALTER TABLE MEMWGONOWNRSHIP   ADD CONSTRAINT PK_MEMWGONOWNRSHIP   PRIMARY KEY (MAVWGONOWNRSHIPCODE);
ALTER TABLE MEMWGONOWNRPRTY   ADD CONSTRAINT PK_MEMWGONOWNRPRTY   PRIMARY KEY (MAVWGONOWNRPRTYCODE);
ALTER TABLE MEMCUSTOMER       ADD CONSTRAINT PK_MEMCUSTOMER       PRIMARY KEY (MAVCUSTOMERCODE);
ALTER TABLE MEMCUSTOMERGSTIN  ADD CONSTRAINT PK_MEMCUSTOMERGSTIN  PRIMARY KEY (GSTINID);

-- Foreign Keys
ALTER TABLE MEMCUSTOMER ADD CONSTRAINT FK_MEMCUSTOMER_GLBLCUST
    FOREIGN KEY (MAVGLBLCUSTCODE) REFERENCES MEMGLBLCUST (MAVGLBLCUSTCODE);
ALTER TABLE MEMCUSTOMER ADD CONSTRAINT FK_MEMCUSTOMER_HNDGAGNT
    FOREIGN KEY (MAVHNDGAGNTCODE) REFERENCES MEMGLBLHNDGAGNT (MAVHNDGAGNTCODE);
ALTER TABLE MEMCUSTOMERGSTIN ADD CONSTRAINT FK_MEMCUSTGSTIN_CUSTOMER
    FOREIGN KEY (MAVCUSTOMERCODE) REFERENCES MEMCUSTOMER (MAVCUSTOMERCODE) ON DELETE CASCADE;

-- Unique Constraints
ALTER TABLE MEMCUSTOMERGSTIN ADD CONSTRAINT UQ_MEMCUSTGSTIN_CUST_GSTIN UNIQUE (MAVCUSTOMERCODE, MAVGSTINNUMBER);
ALTER TABLE MEMCUSTOMER      ADD CONSTRAINT UQ_MEMCUSTOMER_PAN         UNIQUE (MAVPAN);
ALTER TABLE MEMCUSTOMER      ADD CONSTRAINT UQ_MEMCUSTOMER_EMAIL       UNIQUE (MAVEMAIL);

-- Check Constraints
ALTER TABLE MEMCUSTOMER ADD CONSTRAINT CK_MEMCUSTOMER_CODE_PRESENT
    CHECK ((MAVGLBLCUSTCODE IS NOT NULL AND MAVHNDGAGNTCODE IS NULL) OR (MAVGLBLCUSTCODE IS NULL AND MAVHNDGAGNTCODE IS NOT NULL));
ALTER TABLE MEMCUSTOMER      ADD CONSTRAINT CK_MEMCUSTOMER_ACTIVEFLAG    CHECK (MACACTIVEFLAG IN ('Y', 'N'));
ALTER TABLE MEMCUSTOMERGSTIN ADD CONSTRAINT CK_MEMCUSTGSTIN_ACTIVEFLAG   CHECK (MACACTIVEFLAG IN ('Y', 'N'));
ALTER TABLE MEMCUSTOMER      ADD CONSTRAINT CK_MEMCUSTOMER_PAN_FORMAT    CHECK (MAVPAN IS NULL OR REGEXP_LIKE(MAVPAN, '^[A-Z]{5}[0-9]{4}[A-Z]{1}$'));
ALTER TABLE MEMCUSTOMERGSTIN ADD CONSTRAINT CK_MEMCUSTGSTIN_FORMAT       CHECK (REGEXP_LIKE(MAVGSTINNUMBER, '^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[A-Z0-9]{1}[Z]{1}[A-Z0-9]{1}$'));
ALTER TABLE MEMCUSTOMER      ADD CONSTRAINT CK_MEMCUSTOMER_MOBILE        CHECK (MAVMOBILE IS NULL OR REGEXP_LIKE(MAVMOBILE, '^[6-9][0-9]{9}$'));
ALTER TABLE MEMCUSTOMER      ADD CONSTRAINT CK_MEMCUSTOMER_PINCODE       CHECK (MAVPINCODE IS NULL OR REGEXP_LIKE(MAVPINCODE, '^[0-9]{6}$'));
ALTER TABLE MEMCUSTOMER      ADD CONSTRAINT CK_MEMCUSTOMER_PCOCODE       CHECK (MAVPCOCODE IS NULL OR REGEXP_LIKE(MAVPCOCODE, '^[0-9]{2,3}$'));

-- ═══════════════════════════════════════════════════════════════════════════
-- INDEXES (from 03_indexes.sql — omitted for brevity, see 03_indexes.sql)
-- ═══════════════════════════════════════════════════════════════════════════
-- Run 03_indexes.sql separately for all performance indexes.

-- Auth table indexes
CREATE INDEX IDX_MEMUSERS_USERNAME ON MEMUSERS (MAVUSERNAME);
CREATE INDEX IDX_MEMUSERS_EMAIL    ON MEMUSERS (MAVEMAIL);
